[tool.poetry]
name = "pynest-api"
version = "0.1.0"
description = "PyNest is a FastAPI Abstraction for building microservices, influenced by NestJS."
authors = []
license = "MIT"
readme = "README.md"
packages = [ { include = "nest" } ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
repository = "https://github.com/PythonNest/PyNest"
documentation = "https://pythonnest.github.io/PyNest/"

[tool.poetry.dependencies]
python = "^3.8"
click = "==8.1.6"
fastapi = "==0.95.1"
python-dotenv = "==1.0.0"
SQLAlchemy = "==2.0.19"
uvicorn = "==0.23.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "*"
motor = "==3.2.0"
beanie = "==1.20.0"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
black = "==23.1.0"

[tool.poetry.group.codespell]
optional = true

[tool.poetry.group.codespell.dependencies]
codespell = "^2.2.0"

[tool.poetry.group.typing]
optional = true

[tool.poetry.group.typing.dependencies]
mypy = "^0.991"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocstrings-python = "*"
mkdocs-material = "*"

[tool.poetry.scripts]
lemodel = "nest.cli.cli:nest_cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tools.black]
force-exclude = '''
/(
  | /*venv*
  | /.git
  | /dist
  | /pytest_compare.egg-info
  | *.bac
  | .mypy_cache
  | .coverage
  | /htmlcov
  | /docs
  | /site
)/
'''

[tool.mypy]
exclude = [
    "/*venv*"
]
ignore_missing_imports = true
