name: Release Package

on:
  workflow_dispatch:
    permissions:
      users:
        - ItayTheDar

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yaml

  release-package:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Publish package tp Pypi
        run: |
          poetry config http-basic.pypi ${{ secrets.PYPI_API_USER }} ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build

  deploy-docs:
    needs: release-package
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy_docs.yaml
